server:
  port: 801
  
spring:
  datasource:
    url: jdbc:mysql://120.79.45.185:3306/wxdemo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
#开启驼峰标识
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl