package com.wxdemo.model;

import org.springframework.stereotype.Repository;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table choice
 */
@Repository
public class Choice {

	/**
	 * Database Column Remarks: 套餐id This field was generated by MyBatis Generator. This field corresponds to the database column choice.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * Database Column Remarks: 套餐名 This field was generated by MyBatis Generator. This field corresponds to the database column choice.name
	 * @mbg.generated
	 */
	private String name;
	/**
	 * Database Column Remarks: 价格 This field was generated by MyBatis Generator. This field corresponds to the database column choice.price
	 * @mbg.generated
	 */
	private Integer price;
	/**
	 * Database Column Remarks: 定金 This field was generated by MyBatis Generator. This field corresponds to the database column choice.deposit
	 * @mbg.generated
	 */
	private Integer deposit;
	/**
	 * Database Column Remarks: 详细信息 This field was generated by MyBatis Generator. This field corresponds to the database column choice.description
	 * @mbg.generated
	 */
	private String description;
	/**
	 * Database Column Remarks: 注意事项 This field was generated by MyBatis Generator. This field corresponds to the database column choice.care_about
	 * @mbg.generated
	 */
	private String careAbout;
	/**
	 * Database Column Remarks: 套餐照片名 This field was generated by MyBatis Generator. This field corresponds to the database column choice.pack_photo_name1
	 * @mbg.generated
	 */
	private String packPhotoName1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column choice.pack_photo_name2
	 * @mbg.generated
	 */
	private String packPhotoName2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column choice.pack_photo_name3
	 * @mbg.generated
	 */
	private String packPhotoName3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column choice.pack_photo_name4
	 * @mbg.generated
	 */
	private String packPhotoName4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column choice.pack_photo_name5
	 * @mbg.generated
	 */
	private String packPhotoName5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column choice.pack_photo_name6
	 * @mbg.generated
	 */
	private String packPhotoName6;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column choice.pack_photo_name7
	 * @mbg.generated
	 */
	private String packPhotoName7;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column choice.pack_photo_name8
	 * @mbg.generated
	 */
	private String packPhotoName8;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column choice.id
	 * @return  the value of choice.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column choice.id
	 * @param id  the value for choice.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column choice.name
	 * @return  the value of choice.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column choice.name
	 * @param name  the value for choice.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column choice.price
	 * @return  the value of choice.price
	 * @mbg.generated
	 */
	public Integer getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column choice.price
	 * @param price  the value for choice.price
	 * @mbg.generated
	 */
	public void setPrice(Integer price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column choice.deposit
	 * @return  the value of choice.deposit
	 * @mbg.generated
	 */
	public Integer getDeposit() {
		return deposit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column choice.deposit
	 * @param deposit  the value for choice.deposit
	 * @mbg.generated
	 */
	public void setDeposit(Integer deposit) {
		this.deposit = deposit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column choice.description
	 * @return  the value of choice.description
	 * @mbg.generated
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column choice.description
	 * @param description  the value for choice.description
	 * @mbg.generated
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column choice.care_about
	 * @return  the value of choice.care_about
	 * @mbg.generated
	 */
	public String getCareAbout() {
		return careAbout;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column choice.care_about
	 * @param careAbout  the value for choice.care_about
	 * @mbg.generated
	 */
	public void setCareAbout(String careAbout) {
		this.careAbout = careAbout;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column choice.pack_photo_name1
	 * @return  the value of choice.pack_photo_name1
	 * @mbg.generated
	 */
	public String getPackPhotoName1() {
		return packPhotoName1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column choice.pack_photo_name1
	 * @param packPhotoName1  the value for choice.pack_photo_name1
	 * @mbg.generated
	 */
	public void setPackPhotoName1(String packPhotoName1) {
		this.packPhotoName1 = packPhotoName1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column choice.pack_photo_name2
	 * @return  the value of choice.pack_photo_name2
	 * @mbg.generated
	 */
	public String getPackPhotoName2() {
		return packPhotoName2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column choice.pack_photo_name2
	 * @param packPhotoName2  the value for choice.pack_photo_name2
	 * @mbg.generated
	 */
	public void setPackPhotoName2(String packPhotoName2) {
		this.packPhotoName2 = packPhotoName2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column choice.pack_photo_name3
	 * @return  the value of choice.pack_photo_name3
	 * @mbg.generated
	 */
	public String getPackPhotoName3() {
		return packPhotoName3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column choice.pack_photo_name3
	 * @param packPhotoName3  the value for choice.pack_photo_name3
	 * @mbg.generated
	 */
	public void setPackPhotoName3(String packPhotoName3) {
		this.packPhotoName3 = packPhotoName3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column choice.pack_photo_name4
	 * @return  the value of choice.pack_photo_name4
	 * @mbg.generated
	 */
	public String getPackPhotoName4() {
		return packPhotoName4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column choice.pack_photo_name4
	 * @param packPhotoName4  the value for choice.pack_photo_name4
	 * @mbg.generated
	 */
	public void setPackPhotoName4(String packPhotoName4) {
		this.packPhotoName4 = packPhotoName4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column choice.pack_photo_name5
	 * @return  the value of choice.pack_photo_name5
	 * @mbg.generated
	 */
	public String getPackPhotoName5() {
		return packPhotoName5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column choice.pack_photo_name5
	 * @param packPhotoName5  the value for choice.pack_photo_name5
	 * @mbg.generated
	 */
	public void setPackPhotoName5(String packPhotoName5) {
		this.packPhotoName5 = packPhotoName5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column choice.pack_photo_name6
	 * @return  the value of choice.pack_photo_name6
	 * @mbg.generated
	 */
	public String getPackPhotoName6() {
		return packPhotoName6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column choice.pack_photo_name6
	 * @param packPhotoName6  the value for choice.pack_photo_name6
	 * @mbg.generated
	 */
	public void setPackPhotoName6(String packPhotoName6) {
		this.packPhotoName6 = packPhotoName6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column choice.pack_photo_name7
	 * @return  the value of choice.pack_photo_name7
	 * @mbg.generated
	 */
	public String getPackPhotoName7() {
		return packPhotoName7;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column choice.pack_photo_name7
	 * @param packPhotoName7  the value for choice.pack_photo_name7
	 * @mbg.generated
	 */
	public void setPackPhotoName7(String packPhotoName7) {
		this.packPhotoName7 = packPhotoName7;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column choice.pack_photo_name8
	 * @return  the value of choice.pack_photo_name8
	 * @mbg.generated
	 */
	public String getPackPhotoName8() {
		return packPhotoName8;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column choice.pack_photo_name8
	 * @param packPhotoName8  the value for choice.pack_photo_name8
	 * @mbg.generated
	 */
	public void setPackPhotoName8(String packPhotoName8) {
		this.packPhotoName8 = packPhotoName8;
	}
}