package com.wxdemo.model;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.stereotype.Repository;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table orders
 */
@Repository
public class Orders {
	
	/**
	 * Database Column Remarks: order_id This field was generated by MyBatis Generator. This field corresponds to the database column orders.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * Database Column Remarks: Ψһ��ʶ This field was generated by MyBatis Generator. This field corresponds to the database column orders.open_id
	 * @mbg.generated
	 */
	private String openId;
	/**
	 * Database Column Remarks: �ײ�id This field was generated by MyBatis Generator. This field corresponds to the database column orders.choice_id
	 * @mbg.generated
	 */
	private Integer choiceId;
	/**
	 * Database Column Remarks: ԤԼ�� This field was generated by MyBatis Generator. This field corresponds to the database column orders.reserve_name
	 * @mbg.generated
	 */
	private String reserveName;
	/**
	 * Database Column Remarks: �ֻ��� This field was generated by MyBatis Generator. This field corresponds to the database column orders.phone
	 * @mbg.generated
	 */
	private String phone;
	/**
	 * Database Column Remarks: ԤԼʱ�� This field was generated by MyBatis Generator. This field corresponds to the database column orders.start_time
	 * @mbg.generated
	 */
	@DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
	private Date startTime;
	/**
	 * Database Column Remarks: ���ʱ�� This field was generated by MyBatis Generator. This field corresponds to the database column orders.end_time
	 * @mbg.generated
	 */
	@DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
	private Date endTime;
	/**
	 * Database Column Remarks: ���״̬ This field was generated by MyBatis Generator. This field corresponds to the database column orders.status
	 * @mbg.generated
	 */
	private Integer status;
	/**
	 * Database Column Remarks: ֧��״̬ This field was generated by MyBatis Generator. This field corresponds to the database column orders.pay_status
	 * @mbg.generated
	 */
	private Integer payStatus;
	/**
	 * Database Column Remarks: Ԥ��ʱ�� This field was generated by MyBatis Generator. This field corresponds to the database column orders.reserve_time
	 * @mbg.generated
	 */
	@DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
	private Date reserveTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.notes
	 * @mbg.generated
	 */
	private String notes;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.id
	 * @return  the value of orders.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.id
	 * @param id  the value for orders.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.open_id
	 * @return  the value of orders.open_id
	 * @mbg.generated
	 */
	public String getOpenId() {
		return openId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.open_id
	 * @param openId  the value for orders.open_id
	 * @mbg.generated
	 */
	public void setOpenId(String openId) {
		this.openId = openId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.choice_id
	 * @return  the value of orders.choice_id
	 * @mbg.generated
	 */
	public Integer getChoiceId() {
		return choiceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.choice_id
	 * @param choiceId  the value for orders.choice_id
	 * @mbg.generated
	 */
	public void setChoiceId(Integer choiceId) {
		this.choiceId = choiceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.reserve_name
	 * @return  the value of orders.reserve_name
	 * @mbg.generated
	 */
	public String getReserveName() {
		return reserveName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.reserve_name
	 * @param reserveName  the value for orders.reserve_name
	 * @mbg.generated
	 */
	public void setReserveName(String reserveName) {
		this.reserveName = reserveName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.phone
	 * @return  the value of orders.phone
	 * @mbg.generated
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.phone
	 * @param phone  the value for orders.phone
	 * @mbg.generated
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.start_time
	 * @return  the value of orders.start_time
	 * @mbg.generated
	 */
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.start_time
	 * @param startTime  the value for orders.start_time
	 * @mbg.generated
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.end_time
	 * @return  the value of orders.end_time
	 * @mbg.generated
	 */
	public Date getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.end_time
	 * @param endTime  the value for orders.end_time
	 * @mbg.generated
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.status
	 * @return  the value of orders.status
	 * @mbg.generated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.status
	 * @param status  the value for orders.status
	 * @mbg.generated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.pay_status
	 * @return  the value of orders.pay_status
	 * @mbg.generated
	 */
	public Integer getPayStatus() {
		return payStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.pay_status
	 * @param payStatus  the value for orders.pay_status
	 * @mbg.generated
	 */
	public void setPayStatus(Integer payStatus) {
		this.payStatus = payStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.reserve_time
	 * @return  the value of orders.reserve_time
	 * @mbg.generated
	 */
	public Date getReserveTime() {
		return reserveTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.reserve_time
	 * @param reserveTime  the value for orders.reserve_time
	 * @mbg.generated
	 */
	public void setReserveTime(Date reserveTime) {
		this.reserveTime = reserveTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.notes
	 * @return  the value of orders.notes
	 * @mbg.generated
	 */
	public String getNotes() {
		return notes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.notes
	 * @param notes  the value for orders.notes
	 * @mbg.generated
	 */
	public void setNotes(String notes) {
		this.notes = notes;
	}

	private Choice choice;
	
    public Choice getChoice() {
		return choice;
	}

	public void setChoice(Choice choice) {
		this.choice = choice;
	}
}