package com.wxdemo.model;

import org.springframework.stereotype.Repository;

import com.google.gson.annotations.SerializedName;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user
 */
@Repository
public class User {

	/**
	 * Database Column Remarks: �û�id This field was generated by MyBatis Generator. This field corresponds to the database column user.user_id
	 * @mbg.generated
	 */
	private Integer userId;
	/**
	 * Database Column Remarks: �û�΢�ŵ�Ψһ��ʶ This field was generated by MyBatis Generator. This field corresponds to the database column user.open_id
	 * @mbg.generated
	 */
	@SerializedName("openid")
	private String openId;
	/**
	 * Database Column Remarks: ΢���ǳ� This field was generated by MyBatis Generator. This field corresponds to the database column user.wechar_name
	 * @mbg.generated
	 */
	private String wecharName;
	/**
	 * Database Column Remarks: �ֻ��� This field was generated by MyBatis Generator. This field corresponds to the database column user.phone
	 * @mbg.generated
	 */
	private String phone;
	/**
	 * Database Column Remarks: �Ա� This field was generated by MyBatis Generator. This field corresponds to the database column user.gender
	 * @mbg.generated
	 */
	private Integer gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.user_city
	 * @mbg.generated
	 */
	private String userCity;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.user_id
	 * @return  the value of user.user_id
	 * @mbg.generated
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.user_id
	 * @param userId  the value for user.user_id
	 * @mbg.generated
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.open_id
	 * @return  the value of user.open_id
	 * @mbg.generated
	 */
	public String getOpenId() {
		return openId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.open_id
	 * @param openId  the value for user.open_id
	 * @mbg.generated
	 */
	public void setOpenId(String openId) {
		this.openId = openId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.wechar_name
	 * @return  the value of user.wechar_name
	 * @mbg.generated
	 */
	public String getWecharName() {
		return wecharName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.wechar_name
	 * @param wecharName  the value for user.wechar_name
	 * @mbg.generated
	 */
	public void setWecharName(String wecharName) {
		this.wecharName = wecharName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.phone
	 * @return  the value of user.phone
	 * @mbg.generated
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.phone
	 * @param phone  the value for user.phone
	 * @mbg.generated
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.gender
	 * @return  the value of user.gender
	 * @mbg.generated
	 */
	public Integer getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.gender
	 * @param gender  the value for user.gender
	 * @mbg.generated
	 */
	public void setGender(Integer gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.user_city
	 * @return  the value of user.user_city
	 * @mbg.generated
	 */
	public String getUserCity() {
		return userCity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.user_city
	 * @param userCity  the value for user.user_city
	 * @mbg.generated
	 */
	public void setUserCity(String userCity) {
		this.userCity = userCity;
	}
}