package com.wxdemo.model;

import org.springframework.stereotype.Repository;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table works
 */
@Repository
public class Works {
    /**
     * Database Column Remarks:
     *   ����id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   ��������
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   ��Ƭ����
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.photo_name1
     *
     * @mbg.generated
     */
    private String photoName1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.photo_name2
     *
     * @mbg.generated
     */
    private String photoName2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.photo_name3
     *
     * @mbg.generated
     */
    private String photoName3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.photo_name4
     *
     * @mbg.generated
     */
    private String photoName4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.photo_name5
     *
     * @mbg.generated
     */
    private String photoName5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.photo_name6
     *
     * @mbg.generated
     */
    private String photoName6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.photo_name7
     *
     * @mbg.generated
     */
    private String photoName7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.photo_name8
     *
     * @mbg.generated
     */
    private String photoName8;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.id
     *
     * @return the value of works.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.id
     *
     * @param id the value for works.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.name
     *
     * @return the value of works.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.name
     *
     * @param name the value for works.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.photo_name1
     *
     * @return the value of works.photo_name1
     *
     * @mbg.generated
     */
    public String getPhotoName1() {
        return photoName1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.photo_name1
     *
     * @param photoName1 the value for works.photo_name1
     *
     * @mbg.generated
     */
    public void setPhotoName1(String photoName1) {
        this.photoName1 = photoName1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.photo_name2
     *
     * @return the value of works.photo_name2
     *
     * @mbg.generated
     */
    public String getPhotoName2() {
        return photoName2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.photo_name2
     *
     * @param photoName2 the value for works.photo_name2
     *
     * @mbg.generated
     */
    public void setPhotoName2(String photoName2) {
        this.photoName2 = photoName2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.photo_name3
     *
     * @return the value of works.photo_name3
     *
     * @mbg.generated
     */
    public String getPhotoName3() {
        return photoName3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.photo_name3
     *
     * @param photoName3 the value for works.photo_name3
     *
     * @mbg.generated
     */
    public void setPhotoName3(String photoName3) {
        this.photoName3 = photoName3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.photo_name4
     *
     * @return the value of works.photo_name4
     *
     * @mbg.generated
     */
    public String getPhotoName4() {
        return photoName4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.photo_name4
     *
     * @param photoName4 the value for works.photo_name4
     *
     * @mbg.generated
     */
    public void setPhotoName4(String photoName4) {
        this.photoName4 = photoName4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.photo_name5
     *
     * @return the value of works.photo_name5
     *
     * @mbg.generated
     */
    public String getPhotoName5() {
        return photoName5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.photo_name5
     *
     * @param photoName5 the value for works.photo_name5
     *
     * @mbg.generated
     */
    public void setPhotoName5(String photoName5) {
        this.photoName5 = photoName5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.photo_name6
     *
     * @return the value of works.photo_name6
     *
     * @mbg.generated
     */
    public String getPhotoName6() {
        return photoName6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.photo_name6
     *
     * @param photoName6 the value for works.photo_name6
     *
     * @mbg.generated
     */
    public void setPhotoName6(String photoName6) {
        this.photoName6 = photoName6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.photo_name7
     *
     * @return the value of works.photo_name7
     *
     * @mbg.generated
     */
    public String getPhotoName7() {
        return photoName7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.photo_name7
     *
     * @param photoName7 the value for works.photo_name7
     *
     * @mbg.generated
     */
    public void setPhotoName7(String photoName7) {
        this.photoName7 = photoName7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.photo_name8
     *
     * @return the value of works.photo_name8
     *
     * @mbg.generated
     */
    public String getPhotoName8() {
        return photoName8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.photo_name8
     *
     * @param photoName8 the value for works.photo_name8
     *
     * @mbg.generated
     */
    public void setPhotoName8(String photoName8) {
        this.photoName8 = photoName8;
    }
}