package com.wxdemo.mapper;

import com.wxdemo.model.Choice;
import java.util.List;

public interface ChoiceMapper {
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table choice
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table choice
	 * @mbg.generated
	 */
	int insert(Choice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table choice
	 * @mbg.generated
	 */
	Choice selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table choice
	 * @mbg.generated
	 */
	List<Choice> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table choice
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Choice record);

	List<Choice> selectByIdList(List list);
}