package com.wxdemo.mapper;

import com.wxdemo.model.Orders;
import java.util.List;

public interface OrdersMapper {
	
	List<Orders> selectAllByOpenid(String openid);
	
	List<Orders> selectAllDoingByOpenid(String openid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbg.generated
	 */
	int insert(Orders record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbg.generated
	 */
	Orders selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbg.generated
	 */
	List<Orders> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Orders record);
}