package com.wxdemo.mapper;

import com.wxdemo.model.Works;
import java.util.List;

public interface WorksMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table works
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table works
	 * @mbg.generated
	 */
	int insert(Works record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table works
	 * @mbg.generated
	 */
	Works selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table works
	 * @mbg.generated
	 */
	List<Works> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table works
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Works record);
}